### ISSUE TITLE
Can't open settings.

### ISSUE THREAD

**Issue by dowilcox** [negativo17/spotify-client#10]
Nothing happening when clicking on "Settings" from the drop down to the right of my username.

**Comment by bykbtzr** [comment]
This issue is likely to be something between Spotify client and your DE as this repo is only about unpacking the binary and providing dependencies for fedora. 

My guess is that if you're not using GNOME or using Wayland that might be the source of your issue.

**Comment by dowilcox** [comment]
I am currently using GNOME and Wayland. Thought others might be having the same issue.

**Comment by scaronni** [comment]
Are you using Wayland? The client does not support Wayland and it's a binary blob, so unless the issue is about packaging there's not much I can do.
