### ISSUE TITLE
Segfault after pressing "Log In" button

### ISSUE THREAD

**Issue by w4pp** [negativo17/spotify-client#11]
The client simply prints "Segmentation fault (core dumped)" and closes.

Maybe [this](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Liunx-Spotify-Crash-during-start-segfault/td-p/1296846) is related, but starting spotify with --force-device-scaling-factor=1.0000001 doesn't make a difference for me.

**Comment by scaronni** [comment]
Are you using Wayland? The client does not support Wayland and it's a binary blob, so unless the issue is about packaging there's not much I can do.

**Comment by jnatten** [comment]
`I` get this on fedora 25 (on Xorg AND Wayland, 4.8.14-300.fc25.x86_64)
Here is what spotify outputs in a terminal.
Only last line is printed when login button is pressed.
Sorry if it is not your fault/problem and can't help it. Just wanted to let you know.

spotify: /lib64/libssl.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcurl.so.4: no version information available (required by spotify)
/usr/lib64/spotify-client/spotify: /lib64/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
[1217/163240:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
/proc/self/exe: /lib64/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
[1217/163241:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
[1217/163333:ERROR:PlatformKeyboardEvent.cpp(94)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
Segmentation fault (core dumped)

**Comment by josephrobertlopez** [comment]
i've got this problem also. However I did not have it when i initally did a fresh install of fedora 25 on my pc. The error only occurred after I updated from 24 to 25 via command line when I was testing out other bugs on the same computer. 
edit: the problem also occurred when i tried repackaging the binaries.

**Comment by scaronni** [comment]
Works fine here for all features except local files playing (even strace shows no sign of the client trying to do anything locally) but I'm running X.

**Comment by w4pp** [comment]
I have copied the ~/.config/spotify directory from my other pc (still FC24) to my FC25 install, and now spotify starts as expected. So there seems to be an issue with the "Log In" part, but I can't say what is causing the issue.

**Comment by wieczorek1990** [comment]
I've selected X.org session in GDM but the error still occurs after a fresh Fedora 25 Workstation installation.
```
$ spotify
spotify: /lib64/libssl.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcurl.so.4: no version information available (required by spotify)
/usr/lib64/spotify-client/spotify: /lib64/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
[1219/142348:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
/proc/self/exe: /lib64/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
[1219/142348:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
[1219/142350:ERROR:PlatformKeyboardEvent.cpp(94)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
Segmentation fault (core dumped)
```

**Comment by josephrobertlopez** [comment]
I ended up converting the debian package with alien and its working well on wayland for me on fedora 25. however the browse page is blank, social media page is dead and its suck in either full screen or minimized.

**Comment by wieczorek1990** [comment]
How did you get around this error:
```
$ sudo dnf install spotify-client-1.0.45.182.gbbd5909f-73.x86_64.rpm
Last metadata expiration check: 2:54:05 ago on Tue Dec 20 10:38:05 2016.
Error: nothing provides libcrypto.so.1.0.0(OPENSSL_1.0.0)(64bit) needed by spotify-client-1.0.45.182.gbbd5909f-73.x86_64
```

**Comment by wieczorek1990** [comment]
@josephrobertlopez how did you get around this error:
```
$ sudo dnf install spotify-client-1.0.45.182.gbbd5909f-73.x86_64.rpm
Last metadata expiration check: 2:54:05 ago on Tue Dec 20 10:38:05 2016.
Error: nothing provides libcrypto.so.1.0.0(OPENSSL_1.0.0)(64bit) needed by spotify-client-1.0.45.182.gbbd5909f-73.x86_64
```

**Comment by scaronni** [comment]
> @josephrobertlopez how did you get around this error:

Hey, this is not related to the package I'm providing. Anyway it's not so easy as just to convert the package. The versioned libcrypto library is in default OpenSSL packge from Ubuntu, and since Fedora / RHEL do not have version 1.0.0 I'm providing the compat-openssl package.

To avoid the hard requirements on the libraries you should also filter out the other libraries:

https://github.com/negativo17/spotify-client/blob/master/spotify-client.spec#L5-L6

This makes sure that the three versioned libraries (the warnings you see on startup) are filtered from the automatic provide/require at RPM assembly time.

**Comment by wieczorek1990** [comment]
The error happens even if I have the `compat-openssl` package installed.

**Comment by scaronni** [comment]
Re-read please:

> This makes sure that the three versioned libraries (the warnings you see on startup) are
> filtered from the automatic provide/require at RPM assembly time.

At RPM assembly time, not when you install. You need to rebuild the package not just convert it with alien, otherwise the libraries are not filtered.

**Comment by tlegutko** [comment]
Solution to a problem that worked for me (F25 on Wayland) is described here:
http://negativo17.org/spotify-client/comment-page-3/#comment-52600
Code for the lazy:
```
wget -O spotify-client.deb http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.44.100.ga60c0ce1-89_amd64.deb
ar -x spotify-client.deb
tar xf data.tar.gz
sudo cp -r usr/share/spotify/* /lib64/spotify-client/
rm -r usr/ control.tar.gz data.tar.gz debian-binary spotify-client.deb
```

**Comment by scaronni** [comment]
Spotify just released 1.0.45.186.g3b5036d6. They release a new version every 2/3 days, nothing new is added, a lot of things stop working all the time. This can give you an estimate on how much "quality" goes into it. Bah.

I'm building it now, it will be available in a few minutes.

**Comment by marcusklaas** [comment]
The workaround outlined by @tlegutko worked for me. Thanks!

**Comment by sirincan** [comment]
Thanks, it worked.

**Comment by wieczorek1990** [comment]
Login works in ga60c0ce1 with @tlegutko workaround, g3b5036d6 crashes.

**Comment by wieczorek1990** [comment]
Still the settings and profile pages do not show up.

EDIT:

It only works when using X manager.
