### ISSUE TITLE
delta rpm?

### ISSUE THREAD

**Issue by porjo** [negativo17/spotify-client#12]
It'd be great if there was a delta RPM available for this repo. AFAIK this is done by passing `--deltas` to the `createrepo` command when generating the repo XML.

 Thanks!

**Comment by scaronni** [comment]
Added to the next repo regeneration.

**Comment by porjo** [comment]
I pulled a new update today `spotify-client-1.0-6.fc25.x86_64.rpm`, but no sign of a delta rpm...

**Comment by scaronni** [comment]
Just synced, there is deltarpm now with the latest update. Error in a script :/

**Comment by porjo** [comment]
👍 working well now, thanks
