### ISSUE TITLE
Cannot login on F24

### ISSUE THREAD

**Issue by socialdefect** [negativo17/spotify-client#13]
I do get the login screen but when I try to log in the app exits. Terminal output below but if you can tell me how to process some useful output I can 

[adjemin@workstation ~]$ spotify 
spotify: /lib64/libssl.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcurl.so.4: no version information available (required by spotify)
/usr/lib64/spotify-client/spotify: /lib64/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
[1229/200328:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
[1229/200341:ERROR:PlatformKeyboardEvent.cpp(94)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
Segmentation fault (core dumped)
[adjemin@workstation ~]$

**Comment by uros11** [comment]
I have the same problem :( I hope this will get fixed soon

**Comment by marcioAlmada** [comment]
@socialdefect @uros11 this will probably work for you too https://github.com/negativo17/spotify-client/issues/15#issuecomment-269918583

😉

**Comment by noherczeg** [comment]
Can not log in on F25 either. I'm using X though.

**Comment by uros11** [comment]
@marcioAlmada Thank you, im going to try it out.
