### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by kdaker** [negativo17/spotify-client#14]
On high dpi screens, the app UI is very small since it is rendering on a 1x1 ratio with the pixels. Is it possible to support scaling? 

![spotify_ui](https://cloud.githubusercontent.com/assets/905997/21579966/f51955fa-cf84-11e6-9ad3-4c98f2957097.png)

**Comment by scaronni** [comment]
Unfortunately the application is a binary blob compiled for Ubuntu, I'm simply repackaging it for Fedora/RHEL.
You should ask upstream for any change that is not related to packaging, sorry.
