### ISSUE TITLE
Cannot access to configuration on Fedora 25

### ISSUE THREAD

**Issue by sebamoralesasd** [negativo17/spotify-client#16]
I click to the Configuration button and it does not respond. Actually, it does happen with any button from the top right menu.

**Comment by scaronni** [comment]
Does it work for you in the latest 1.0.47.13.gd8e05b1f?

**Comment by sebamoralesasd** [comment]
Updated to latest release (1.0.47.13.gd8e05b1f), same problem.

**Comment by psukys** [comment]
Can confirm that the buttons from the top-right drop-down menu do not respond after clicking them.
This includes: "Private session", "Account", "Settings" and "Logout"

**Comment by MarekIgnaszak** [comment]
Same here: fedora 24, Spotify version 1.0.47.13.gd8e05b1f

**Comment by psukys** [comment]
The problem seems to be related to using Wayland, as I was able to use the menu and settings on Xorg.

**Comment by sebamoralesasd** [comment]
Would you explain how did you resolve this, please? I have no idea.

**Comment by psukys** [comment]
@sebamoralesasd on login screen, choose X environment instead of Wayland

**Comment by sebamoralesasd** [comment]
It worked! Thank you!

**Comment by scaronni** [comment]
If you need Wayland support, I'm sorry but you need to open a bug to Spotify itself.
