### ISSUE TITLE
can't open settings 

### ISSUE THREAD

**Issue by ricklamers** [negativo17/spotify-client#18]
First of all, thanks for making Spotify available on Fedora.

Second, I ran into the issue of not being able to use any of the drop-down menu items in the upper right hand corner next to the logged in user's profile.

I don't know whether that issue present for everyone. Because of it, I'm not able to access the settings view. Can't check playback quality, etc.

I'd like to know whether this is truly a bug or me f'ing up (most likely).

Kind regards,

**Comment by scaronni** [comment]
Hello, the client does not work properly on Wayland. By chance, are you using an X.org or a Wayland session?

**Comment by ricklamers** [comment]
Wayland session on Fedora 25 idd. Will it be fixed in the future, or no outlook yet?

**Comment by scaronni** [comment]
No clue. The client is a binary blob compiled for Ubuntu, there's no insight on development or features.
