### ISSUE TITLE
Closing spotify issue

### ISSUE THREAD

**Issue by Gobonoid** [negativo17/spotify-client#19]
After closing spotify music is still playing - process is running but I am unable to stop music from notification panel. I can start spotify again and play two songs at once. Any help?

**Comment by JoaaoVerona** [comment]
Same happens to me, using Fedora 24, but it's been like this since when I used it with Fedora 23 some time ago.

Most of the times I have to **kill** the Spotify CEF main process (yeah, *terminating* it is not enough since it appears to be unresponsive)

**Comment by scaronni** [comment]
Please reopen if you still have.
