### ISSUE TITLE
Music pauses and audio stops working

### ISSUE THREAD

**Issue by gaigelama** [negativo17/spotify-client#2]
Music pauses and audio stops working after I adjust volume. Audio doesn't return on play though and I need to completely restart Spotify for it to work again.

Fedora 24:
  compat-libgcrypt.x86_64 1.5.5-5.fc24  
  spotify-client.x86_64 1.0.32.96.g3c8a06e6-1.fc24

**Comment by bykbtzr** [comment]
I've updated to 1.0.32.96 and don't have this issue.
Keep `mesg -wH` and/or journal open and check if something shows up in there when the issue happens again...

**Comment by scaronni** [comment]
Sorry for the late reply. Latest version is 1.0.38.171.

I'm sorry, but the client is a binary blob compiled for Ubuntu. What I'm providing is a re-package for Fedora (with a lot of caveats). If you have an issue with the player itself you should contact Spotify directly as there's nothing I can do.
