### ISSUE TITLE
Spotify segmentation fault on Fedora 27

### ISSUE THREAD

**Issue by anassahmed** [negativo17/spotify-client#24]
I've just upgraded my Fedora machine to 27 and noticed that Spotify client had been updated too, but when I run it, it crashes just right away.

I ran it from the command line to observe what happens:
```bash
$ spotify --log-file=spotify.log --trace-file=spotify-trace.log
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/proc/self/exe: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
[1005/150709.049726:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[1]    24404 segmentation fault (core dumped)  spotify --log-file=spotify.log --trace-file=spotify-trace.log
```

The log file is attached, but the trace file hasn't been created for some reason.

[spotify.log](https://github.com/negativo17/spotify-client/files/1359413/spotify.log)

**Comment by anassahmed** [comment]
**Update:** I tried deleting `~/.config/spotify` and `~/.cache/spotify` to prevent any unexpected configurations from causing any trouble but the application still gives me segmentation fault (core dumped).

**Comment by scaronni** [comment]
Hello, are you running it under Wayland?

**Comment by anassahmed** [comment]
@scaronni Yes, but so is the previous version on Fedora 26 that was working pefectly. I'm using Wayland session exclusively since Fedora 24 actually.

**Comment by anassahmed** [comment]
I noticed new updates for `spotify-openssl` and `spotify-ffmpeg` packages, so I tried to fire up the application again; attached is the log after the crash.

[spotify.log](https://github.com/negativo17/spotify-client/files/1361402/spotify.log)

**Comment by anassahmed** [comment]
I've just tried to open Spotify client under Xorg session and it also crashed!

I don't think this issue is related to using Wayland here.

**Comment by basvd** [comment]
This is possibly due to an incompatible version of libcurl. I had the same issue and fixed it after seeing [this comment](https://negativo17.org/spotify-client/comment-page-3/#comment-53332) on the spotify-client page.

Download the [_libcurl_ package for fedora 26](https://apps.fedoraproject.org/packages/curl), extract the `./usr/lib64/*.so` files to `/usr/lib64/spotify-client` and see if that works.

**Comment by scaronni** [comment]
Actually this came out months ago, but there was no issue opened so I completely forgot about it.

Can you try again with the updates that I just pushed? It contains also a specific `libcurl` version built from Fedora 26 sources.

**Comment by anassahmed** [comment]
Yes, it finally works again, with the update to the package: `spotify-client-1.0-22.fc27.x86_64` which installed the package `spotify-curl-7.53.1-1.fc27.x86_64` as a new dependency.

Thanks, @scaronni.

I hope you point people to Github issues here to report bugs so you can easily track the bugs better than WP comments or private emails.
