### ISSUE TITLE
Seg fault fedora 27

### ISSUE THREAD

**Issue by alexillsley** [negativo17/spotify-client#25]
Hi, 
After the login page I get segmentation fault and window closes. How to fix this?

See debug information below:

 rpm -qa|grep spotify
spotify-client-1.0.66.478.g1296534d-1.el7.x86_64
spotify-ffmpeg-0.10.16-3.el7.x86_64
spotify-openssl-1.0.0t-4.el7.x86_64

cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)

spotify
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
Segmentation fault (core dumped)

[@localhost ~]$ gdb /usr/lib64/spotify-client/spotify 
GNU gdb (GDB) Fedora 8.0.1-30.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib64/spotify-client/spotify...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/lib64/spotify-client/spotify 
Missing separate debuginfos, use: dnf debuginfo-install spotify-client-1.0.66.478.g1296534d-1.el7.x86_64
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe0fc9700 (LWP 4175)]
[Thread 0x7fffe0fc9700 (LWP 4175) exited]
[New Thread 0x7fffe0fc9700 (LWP 4176)]
Detaching after fork from child process 4177.
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
[New Thread 0x7fffd2bde700 (LWP 4180)]
[New Thread 0x7fffd23dd700 (LWP 4181)]
[New Thread 0x7fffd1bdc700 (LWP 4182)]
[New Thread 0x7fffd13db700 (LWP 4183)]
[New Thread 0x7fffd0bda700 (LWP 4184)]
[New Thread 0x7fffbbfff700 (LWP 4185)]
[New Thread 0x7fffb3fff700 (LWP 4186)]
[New Thread 0x7fffbb7fe700 (LWP 4187)]
[New Thread 0x7fffbaffd700 (LWP 4188)]
[New Thread 0x7fffba7fc700 (LWP 4189)]
[New Thread 0x7fffb9ffb700 (LWP 4190)]
[New Thread 0x7fffb97fa700 (LWP 4191)]
[New Thread 0x7fffb8ff9700 (LWP 4192)]
[New Thread 0x7fffb37fe700 (LWP 4193)]
[New Thread 0x7fffb2ffd700 (LWP 4194)]
[New Thread 0x7fffb27fc700 (LWP 4195)]
[New Thread 0x7fffb1ffb700 (LWP 4196)]
[New Thread 0x7fffb17fa700 (LWP 4197)]
Detaching after fork from child process 4198.
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
[New Thread 0x7fff83d56700 (LWP 4200)]
[New Thread 0x7fff8312a700 (LWP 4202)]
[New Thread 0x7fff82929700 (LWP 4203)]
[New Thread 0x7fff81bed700 (LWP 4204)]
[New Thread 0x7fff813ec700 (LWP 4205)]
[New Thread 0x7fff57fff700 (LWP 4209)]
[New Thread 0x7fff577fe700 (LWP 4210)]
[New Thread 0x7fff56ffd700 (LWP 4211)]
[New Thread 0x7fff567fc700 (LWP 4212)]
[New Thread 0x7fff55d3a700 (LWP 4229)]
[Thread 0x7fff55d3a700 (LWP 4229) exited]
[New Thread 0x7fff55d3a700 (LWP 4230)]
[New Thread 0x7fff55539700 (LWP 4231)]
[New Thread 0x7fff3ffff700 (LWP 4232)]
[New Thread 0x7fff3f7fe700 (LWP 4233)]
[New Thread 0x7fff3effd700 (LWP 4234)]
[New Thread 0x7fff3e7fc700 (LWP 4235)]
[New Thread 0x7fff3dffb700 (LWP 4237)]
[New Thread 0x7fff3d7fa700 (LWP 4266)]
[Thread 0x7fff3d7fa700 (LWP 4266) exited]

Thread 27 "Default Worker " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff57fff700 (LWP 4209)]
0x00007fffeafafbc0 in ?? () from /lib64/libssl.so.1.1
(gdb) bt
#0  0x00007fffeafafbc0 in ?? () from /lib64/libssl.so.1.1
#1  0x00007fffef10d42c in SSL_CTX_new () from /usr/lib64/spotify-client/libssl.so.1.0.0
#2  0x00007ffff74986b9 in ossl_connect_step1 () from /lib64/libcurl.so.4
#3  0x00007ffff749bebf in ossl_connect_common () from /lib64/libcurl.so.4
#4  0x00007ffff749d301 in Curl_ssl_connect_nonblocking () from /lib64/libcurl.so.4
#5  0x00007ffff744e9d2 in https_connecting () from /lib64/libcurl.so.4
#6  0x00007ffff7461f06 in Curl_protocol_connect () from /lib64/libcurl.so.4
#7  0x00007ffff7476866 in multi_runsingle () from /lib64/libcurl.so.4
#8  0x00007ffff74777b4 in curl_multi_perform () from /lib64/libcurl.so.4
#9  0x00007ffff746d69a in curl_easy_perform () from /lib64/libcurl.so.4
#10 0x00000000015bc3a9 in ?? ()
#11 0x00000000015bc361 in ?? ()
#12 0x00000000015bc349 in ?? ()
#13 0x00000000015bc229 in ?? ()
#14 0x00000000015bc184 in ?? ()
#15 0x00000000015bc0fd in ?? ()
#16 0x00000000016d7db2 in ?? ()
#17 0x00000000016d7d89 in ?? ()
#18 0x00000000016d7d31 in ?? ()
#19 0x00000000016d7c6c in ?? ()
#20 0x0000000000667dc0 in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) ()
#21 0x000000000066798a in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) ()
#22 0x00000000006676a5 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
#23 0x00000000006675f6 in boost::asio::io_service::run() ()
#24 0x00000000016d8cf5 in ?? ()
#25 0x00000000016d8cb3 in ?? ()
#26 0x00000000016d8c89 in ?? ()
#27 0x00000000016d8c69 in ?? ()
#28 0x00000000016d8bad in ?? ()
#29 0x00007fffebeeb390 in ?? () from /lib64/libstdc++.so.6
#30 0x00007fffeeaf5609 in start_thread () from /li

**Comment by scaronni** [comment]
Sorry, many updates since that.
