### ISSUE TITLE
"Log in with Facebook" does not work

### ISSUE THREAD

**Issue by EliaGeretto** [negativo17/spotify-client#26]
When pressing the "Log in with Facebook" button in the login form, nothing happens. Previously, a new window appeared allowing to enter the credentials for Facebook. I am having this problem on Fedora 28, please let me know if the issue is reproducible on your side and if you need further investigation.

**Comment by scaronni** [comment]
Are you using an X or Wayland session?

**Comment by EliaGeretto** [comment]
It does not matter, it happens with both from what I remember. If you need further testing, just ask and I can give you the results tomorrow.

**Comment by mcortinas** [comment]
i'm using KDE and I have a similar errror. Let me attach an screenshot of my error 18.
I also enabled the firewall rules  with 
> sudo firewall-cmd --zone=public --add-service=spotify --permanent
> sudo firewall-cmd --zone=public --add-service=spotify 

![spotifyerror](https://user-images.githubusercontent.com/692263/44472672-e7a72f00-a62e-11e8-8d85-242c19ae8f85.png)

**Comment by EliaGeretto** [comment]
I just checked and, with the last version of the package, I get exactly the same message. The current behaviour is different from the one present when I reported the issue, probably due to the update to the newest version that was made a couple of days ago.

**Comment by scaronni** [comment]
The firewall rules are just for enabling Spotify access on the network (wireless speakers, local file listenting, etc.), it has nothing to do with the Facebook login. The message in the red box actually means that the client cannot reach whatever login endpoint is looking for and thus suggests setting up the proxy correctly.

**Comment by scaronni** [comment]
Btw, I'm just repackaging the Ubuntu binaries in Fedora, so there is no way for me to have any control on the package or report bugs on an unsupported platform, so you're pretty much on your own.

**Comment by scaronni** [comment]
There is a minor update just released, please check if it fixes things for you.

**Comment by EliaGeretto** [comment]
I still see the same red error message as in the screenshot above. Are you able to reproduce the issue on your side though? I just want to be sure it's not some weird interaction that happens only on our installations.

**Comment by scaronni** [comment]
I don't have Facebook, sorry.

**Comment by EliaGeretto** [comment]
Oh, there is no need for that, it is sufficient for you to log out from your real Spotify account and then try to press the "Log in with Facebook" button, no Facebook account is required. A browser window is supposed to pop up, prompting you to insert your Facebook credentials, but instead the red error message will appear.

**Comment by scaronni** [comment]
I tried, same issue as you. Cleaning the whole configuration, starting fresh, tracing the program... same issue.

**Comment by EliaGeretto** [comment]
Ok, at least we have confirmation, thank you.

**Comment by mcortinas** [comment]
The workaround proposed by @ouned in https://github.com/flathub/com.spotify.Client/issues/36 works for me too. It's just a temporary solution, but thanks!

**Comment by scaronni** [comment]
Is this still an issue?

**Comment by voedev** [comment]
> Is this still an issue?

This issue is no longer relevant and can be closed. Authorization with facebook works
