### ISSUE TITLE
Fedora 29 beta - observations

### ISSUE THREAD

**Issue by patchon** [negativo17/spotify-client#28]
Hi, 

Great job making Spotify easy to use for us Fedora users. 
As an relatively early adopter of Fedora 29 I noted a few issues, you may already know about them but I figure I could share them anyway. 

On a ***fresh*** Fedora 29 beta install, I had to do the following to get Spotify to work, 
```
$ > dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
$ > sudo dnf install spotify-client 
Last metadata expiration check: 0:03:22 ago on Sun 30 Sep 2018 04:55:55 PM CEST.
Error: 
 Problem: conflicting requests
  - nothing provides spotify-curl(x86-64) needed by spotify-client-1:1.0.89.313.g34a58dea-1.fc29.x86_64
  - nothing provides spotify-ffmpeg(x86-64) needed by spotify-client-1:1.0.89.313.g34a58dea-1.fc29.x86_64

# Looking at, https://negativo17.org/repos/spotify/fedora-29/x86_64/ we can see that those rpm's are missing. So, I forced the install of the spotify-client-1:1.0.89.313.g34a58dea-1.fc29.x86_64 instead. 
$ > sudo rpm -Uvh https://negativo17.org/repos/spotify/fedora-29/x86_64/spotify-client-1.0.89.313.g34a58dea-1.fc29.x86_64.rpm --nodeps

# Installed other dependencies manually, 
$ > sudo dnf install libatomic libXScrnSaver 

# Linked the curl-library to the one spotify requires (for whatever reason?) 
$ > sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4

# Starting Spotify now works as expected, 
$ > spotify 
/usr/lib64/spotify-client/spotify: /lib64/libcurl-gnutls.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl-gnutls.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/proc/self/exe: /lib64/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0930/170549.133979:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
```
I know its hack to just link Fedora's libcurl (which is linked against openssl) to match the library that the Spotify-binary is linked against (Debian's libcurl which is linked against GnuTLS) - but non the less it works and I'm not really sure why it wouldn't (as long as the spotify-binary doesn't use any weird ***specific GnuTLS*'* functionality (whatever that might be?)) - they both provide the curl library. 

May I ask why you have chosen to separate the curl & ffmpeg libraries into separate packages, wouldn't it be simpler to just keep everything in one package (not sure ffmpeg libs are needed in Fedora 29) ?  

Anyway, awesome work with this - thanks a bunch!

**Comment by scaronni** [comment]
Hello,

the binary is built on Ubuntu and expect Ubuntu binaries for the most part. Many are interchangeable, but not everything. I've added the missing packages, they are available in the repository now. I'm not yet finished with Fedora 29 :/

Remove the Curl link you just created and reinstall ``spotify-client`` to get the dependencies.

FFMpeg binaries are required for importing songs into Spotify, but I don't want to use a fully fledged set of libraries that would require you to install also the multimedia repository.

FFMpeg libraries are loaded on access and you can get a list of what is supported by the binary like this:

```
$ strings /usr/lib64/spotify-client/spotify | grep libav
libavcodec-ffmpeg.so.56
libavcodec.so.54
libavcodec.so.53
libavcodec.so.52
libavformat-ffmpeg.so.56
libavformat.so.54
libavformat.so.53
libavformat.so.52
```

So no chance but build an old release of FFMpeg with minimal dependencies. It can probably be updated, it's on my todo list along with the other ``spotify-*`` packages.
