### ISSUE TITLE
Spotify's output volume is constant, regardless of system's master volume

### ISSUE THREAD

**Issue by BroderickBeaman** [negativo17/spotify-client#3]
No matter what the system's output volume level is, the output to external devices is completely dictated by Spotify's volume level. I noticed this because the media keys on my keyboard would control both Spotify's and the system's master volume levels, but then the levels would start to drift. One could be listening to music and then be deafened by another app's notification. 

You could further try to set the master volume to a reasonable level and set Spotify's output to maximum. One could reason that you should be able to then control Spotify's volume with just the system's master volume but this isn't the case. Spotify's output volume would completely ignore the system's maximum output.

I am using Fedora 23

**Comment by bykbtzr** [comment]
Reseting pulseaudio **after** starting spotify alters the behavior?
`sudo killall -9 pulseaudio`

**Comment by scaronni** [comment]
I don't think there's much I can do there... I'm just repackaging Spotify's binary blobs, so I can't change the behaviour of the program. Is there a setting somewhere which we can use to specify PulseAudio settings?
