### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by RixzZ** [negativo17/spotify-client#30]
Hello.

Seems like a new version (1.1.10.540) is out. They change how 'Liked Songs' works and made it a bit like it worked years ago

Can you update the package?

Thanks!

**Comment by scaronni** [comment]
Where do you see that? I still see the version from the 30th of April:

http://repository.spotify.com/pool/non-free/s/spotify-client/

**Comment by scaronni** [comment]
Also snapcraft has the same version.

**Comment by RixzZ** [comment]
Ops, seems like that version is only released on Windows (an maybe macOS) at this moment.

The app from the Microsoft Store is the one I saw with that version. Sorry,  I didn't know they do releases with different schedules on different platform.
