### ISSUE TITLE
Fedora 32 repository

### ISSUE THREAD

**Issue by dreua** [negativo17/spotify-client#31]
Hey, first of all thank you for maintaining and hosting this packet! 
Since Fedora 32 came out yesterday dnf keeps complaining because it can't find a Fedora 32 spotify repository. I could temporarily change my repo file to point to the 31 version but if you don't mind adding a repository for Fedora 32 (or maybe just a symlink?) that would be the better solution imo. 

Best regards
David

**Comment by scaronni** [comment]
Done, sorry for the delay. It was built a month ago but not pushed.
