### ISSUE TITLE
dependency issue with new spotify version 1.2.20

### ISSUE THREAD

**Issue by h3o66** [negativo17/spotify-client#35]
Seems like the new spotify version has a new dependency what is not provided by the fedora repos:

Problem: cannot install the best update candidate for package spotify-client-1:1.2.13.661.ga588f749-1.fc38.x86_64
  - nothing provides libayatana-appindicator3.so.1()(64bit) needed by spotify-client-1:1.2.20.1210.g2a8a8a57-1.fc38.x86_64
 
not sure how to solve this yet, maybe a additional repo or a change for the existing package is needed

**Comment by allenatdecisiv** [comment]
@h3o66,

Yeah, so there's a shift to change the application indicator and Fedora is late to the party. There is a BZ for it: https://bugzilla.redhat.com/show_bug.cgi?id=1651349

You can find these packages in COPR and rebuild yourself:
https://copr.fedorainfracloud.org/coprs/till/xpad/packages/

**EDIT** I see that you are on Fedora 38, so you can download Till's packages directly (and install them) or add his COPR to your system (he's building for Fedora 38).

Unless @scaronni adds them to his repos?

**Comment by voedev** [comment]
@allenatdecisiv Thank you for sharing the links

**Comment by scaronni** [comment]
Sorry I added custom builds a few hours ago. I will remove them if they end up in Fedora.
