### ISSUE TITLE
Updating spotify-client to version 1.2.22.982.g794acc0a

### ISSUE THREAD

**Issue by voedev** [negativo17/spotify-client#36]
Please, update the spotify client to version 1.2.22.982.g794acc0a

https://snapcraft.io/spotify

![2023-10-10_21-30](https://github.com/negativo17/spotify-client/assets/42519520/0eb369cf-6754-490f-91ad-3510e181e0d1)

**Comment by scaronni** [comment]
Will be online soon. Thanks.
