### ISSUE TITLE
Updating spotify-client to version 1.2.31.1205.g4d59ad7c

### ISSUE THREAD

**Issue by voedev** [negativo17/spotify-client#37]
Please, update the spotify client to version 1.2.31.1205.g4d59ad7c

https://snapcraft.io/spotify

Thank you ❤️

**Comment by scaronni** [comment]
Hi, sorry I'm on holiday until the 3rd of March, so it won't happen before.

**Comment by scaronni** [comment]
Coming online in a few minutes.

**Comment by voedev** [comment]
> Coming online in a few minutes.

Thank you so much!!
