### ISSUE TITLE
AArch64 Support for Fedora

### ISSUE THREAD

**Issue by miyurusankalpa** [negativo17/spotify-client#38]
Hi,

Is is possible to add AArch64 support to install spotify on Fedora Asahi Remix?

Thanks.

**Comment by scaronni** [comment]
If Spotify eventually releases an aarch64 binary, then yes. This is not the case at the moment (click on the version up on the right in this page: https://snapcraft.io/spotify)

**Comment by scaronni** [comment]
Btw, I've built every repository for aarch64 as well (where possible) but I don't have any (decent) arm desktop, so any feedback is appreciated. Thanks.
