### ISSUE TITLE
Installing 1:1.2.45.454.gc16ec9f6-1.fc40.x86_64  via DNF fails with an error

### ISSUE THREAD

**Issue by danieldemus** [negativo17/spotify-client#39]
$ dnf install spotify-client 
Error: 
 Problem: conflicting requests
  - nothing provides spotify-curl(x86-64) needed by spotify-client-1:1.2.45.454.gc16ec9f6-1.fc40.x86_64 from fedora-spotify
(try to add '--skip-broken' to skip uninstallable packages)

This is on a fresh install

**Comment by scaronni** [comment]
Sorry i forgot to trigger the rebuild before removing the dependencies from the repository. New update that does not require `spotify-curl` online in a few minutes.
