### ISSUE TITLE
Consider setting --force-device-scale-factor on Hi-DPI devices

### ISSUE THREAD

**Issue by mattiasb** [negativo17/spotify-client#4]
Hi!

Spotify (or maybe QT apps in general?) has a flag `--force-device-scale-factor` that I can use like below to get Spotify properly scaled on my HiDPI screen:

```
spotify --force-device-scale-factor=\
    $(gsettings get org.gnome.desktop.interface scaling-factor| sed --posix 's/.* \([0-3]\)/\1/g')
```

Would it make sense to change the default .deskop file to do something similar?

**Comment by scaronni** [comment]
Sure, I will try this evening on my non-HiDPI monitor. What is the resolution/size of your display?

Can this applied by default to all QT apps on a system? I guess you will have the same problem everywhere.

**Comment by mattiasb** [comment]
Hm, I have no idea, I don't run any QT applications except for Spotify. When I run `ldd /usr/bin/spotify` there's not a mention of QT even, so not sure it's even using QT anymore?

**Comment by scaronni** [comment]
The parameter you're passing is only specific to gnome, if gnome is not installed that scaling factor is not available, I can't add it by default. Btw, Spotify does not seem to be in QT anymore.

**Comment by bykbtzr** [comment]
I believe it's based on [CEF](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework) now (like electron apps).

**Comment by mattiasb** [comment]
Ah!
