### ISSUE TITLE
Buttons forward and backward not aligned

### ISSUE THREAD

**Issue by kangoula** [negativo17/spotify-client#6]
It's a minor issue, but on Fedora 23+, I experience an issue with the buttons forward and backward. 
![capture du 2016-08-02 21-10-07](https://cloud.githubusercontent.com/assets/9341230/17341608/a6eae0ac-58f5-11e6-8535-f3838c9b3284.png)

**Comment by bykbtzr** [comment]
negativo17 only repacks the binaries released for Ubuntu so they can be installed in Fedora, nothing else. This repository is only to issues related to that (e.g missing dependencies, etc).

The Linux client has no official support from Spotify, so I believe that your best chance is to contact Spotify support directly so maybe they can at least make the dev team get to know about it. But as you can imagine their interest in improving user experience on Linux is nearly non-existent. However I encourage you to go ahead and report it, it may help them to notice that there is a considerable number of paying customers under Linux platform and maybe care more about them in the future. Thanks!

**Comment by kangoula** [comment]
Thanks for the answer, I'll try to contact the support in that case :-) 
I close the issue
