### ISSUE TITLE
Lyrics feature missing

### ISSUE THREAD

**Issue by jmarinho73** [negativo17/spotify-client#7]
I'm a recent Fedora user, since this current version (24) was out and this feature never works for me. Now I have the last version installed (1.0.36.120.g536a862f-1.fc24), but with the previous was the same. I have lubuntu 14.04 installed on other computer and lyrics feature works.

Thanks in advance and sorry for my bad English

**Comment by bykbtzr** [comment]
The lyrics feature was removed by Spotify for [unknown reasons](http://www.digitalmusicnews.com/2016/06/02/spotify-ditched-musixmatch/).

**Comment by jmarinho73** [comment]
Ok. I didn't know it.
Thanks for the quick response. I'll close the issue then.
