### ISSUE TITLE
Time slider of player stuck after ads

### ISSUE THREAD

**Issue by hegerj** [negativo17/spotify-client#8]
After one Ad ended, time slider got stuck at the end position and was not usable afterwards even though Spotify work as if nothing is wrong. I could sop/resume songs, skip them as normally but I couldn't skip within a song. Also timer was stuck at 0:29 time and never changed as another songs started to play.

Fedora 24
spotify-client-1.0.38.171.g5e1cd7b2-4.fc24.x86_64

**Comment by scaronni** [comment]
I'm sorry, but the client is a binary blob compiled for Ubuntu. What I'm providing is a re-package for Fedora (with a lot of caveats). If you have an issue with the player itself you should contact Spotify directly as there's nothing I can do.
