### ISSUE TITLE
Can't play local files. Possible dependency problem.

### ISSUE THREAD

**Issue by sebbasttian** [negativo17/spotify-client#9]
I'm using Fedora 25 with ffmpeg and spotify installed from this repos.

```shell 
~$ sudo dnf list installed '*ffmpeg*'
Last metadata expiration check: 0:02:01 ago on Mon Dec 12 23:47:14 2016.
Installed Packages
ffmpeg.x86_64                      1:3.2.2-1.fc25              @fedora-HandBrake
ffmpeg-devel.x86_64                1:3.2.2-1.fc25              @fedora-HandBrake
ffmpeg-libs.i686                   1:3.2.2-1.fc25              @fedora-HandBrake
ffmpeg-libs.x86_64                 1:3.2.2-1.fc25              @fedora-HandBrake
gstreamer-ffmpeg.x86_64            0.10.13-16.fc25             @@commandline    

~$ sudo dnf list installed '*spotify*'
Last metadata expiration check: 0:02:20 ago on Mon Dec 12 23:47:14 2016.
Installed Packages
spotify-client.x86_64        1.0.43.125.g376063c5-1.fc25         @fedora-spotify

~$ sudo find /usr -type f -iname '*libavformat*'
/usr/lib/libavformat.so.57.56.100
/usr/lib64/pkgconfig/libavformat.pc
/usr/lib64/libavformat.so.57.56.100
/usr/share/doc/ffmpeg-devel/html/libavformat.html
/usr/share/man/man3/libavformat.3.gz

~$ sudo find /usr -type f -iname '*libavcodec*' 
/usr/lib/libavcodec.so.57.64.101
/usr/lib64/pkgconfig/libavcodec.pc
/usr/lib64/libavcodec.so.57.64.101
/usr/share/doc/ffmpeg-devel/html/libavcodec.html
/usr/share/man/man3/libavcodec.3.gz

```
Apparently this is because the client try to use a specific version of `libavcodec` and `libavformat` that are outdated: https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Linux-Local-files-do-not-play-on-Ubuntu-16-04-SOLVED/td-p/1343831

But if I'm not mistaken those versions are not used since Fedora 20.

The client log doesn't show any usefull info:

```
03:01:23.669 D [gaia_manager.cpp:2080           ] GAIA: GaiaManager::becomeActiveDevice, isActiveDevice=false
03:01:23.670 D [gaia_manager.cpp:1025           ] GAIA:   current state ID updated to -165633838
03:01:23.682 I [audio_driver_linux.cpp:18       ] Using PulseAudio
03:01:23.682 I [audio_player_queue_impl.cpp:242 ] Pause driver: 0x00007f60a8868030
03:01:23.683 I [audio_player_queue_entry.cpp:323] Buffering changed for entry: 0x00007f60a82694c0, 1
03:01:23.683 I [audio_player_queue_impl.cpp:313 ] fade in at -1 for -1 milliseconds, fade out at -1 for -1 milliseconds
03:01:23.683 I [audio_player_queue_impl.cpp:836 ] Pause driver: 0x00007f60a8868030, 0
03:01:23.683 D [gaia_manager.cpp:1025           ] GAIA:   current state ID updated to -165633824
03:01:23.685 I [sliding_window_prefetch_strategy.cpp:213] Prefetch: looks like new context - resetting window size to 1
03:01:23.689 I [logger_impl_base.cpp:64         ] Saved 1 log messages to '/home/sebs/.config/spotify/Users/nsebs-user/log-tracked'
03:01:23.690 I [logger_impl_base.cpp:64         ] Saved 1 log messages to '/home/sebs/.config/spotify/Users/nsebs-user/log-tracked'
03:01:23.690 D [gaia_manager.cpp:1025           ] GAIA:   current state ID updated to -165633817
03:01:23.690 I [sliding_window_prefetch_strategy.cpp:213] Prefetch: looks like new context - resetting window size to 1
```

Thanks in advance.

**Comment by scaronni** [comment]
Hello, Spotify requires FFMpeg versions lower than 3.1 to play local files. I've put a "Recommends" on `compat-ffmpeg-libs` so you can use the repository alone without any extra repository required. With the multimedia repository installed (like you do), just do:

`dnf install compat-ffmpeg-libs`

And you should be able to play local files.

**Comment by sebbasttian** [comment]
Thanks for replying so quick.

But this doesn't solve the problem (at least for me). I installed both i686 and x86_64 packages and I still can't play local files.

**Comment by scaronni** [comment]
Ok, I've added some content to Spotify, it indeed does not work. It reads the files but just says that they need to be present on the filesystem (wtf?).

This should be the normal behaviour, spotify dlopens the FFmpeg libraries:

```
$ strings /usr/lib64/spotify-client/spotify | grep libav
libavcodec.so.56
libavcodec.so.54
libavcodec.so.53
libavcodec.so.52
libavformat.so.56
libavformat.so.54
libavformat.so.53
libavformat.so.52
$ rpm -ql compat-ffmpeg-libs | egrep "libavcodec|libavformat"
/usr/lib64/libavcodec.so.56
/usr/lib64/libavcodec.so.56.60.100
/usr/lib64/libavformat.so.56
/usr/lib64/libavformat.so.56.40.101
```

It used to work, but it does not at the moment, so I guess that the only thing we can do is to hope they fix it in the next build. Keep in mind that this is a repackaged Ubuntu binary program.

**Comment by scaronni** [comment]
Oh well, I've traced the client and it does not even attempt to load the libraries....

**Comment by wieczorek1990** [comment]
Same issue, fresh install; installing `compat-ffmpeg-libs` does not help at all.

**Comment by jrupinski** [comment]
Problem still persists on Fedora 25 (wayland), _`compat-ffmpeg-libs`_ does not fix the problem.

**Comment by scaronni** [comment]
After rebuild after rebuild and attempt after attempt I've discovered that Spotify local files can play with an ancient FFmpeg 0.10.x build without external dependencies. But unlike OpenSSL or the other libraries, those are dynamically loaded from the system path.

I've uploaded a new build that has this new package without external dependencies in it, it fixed local files playing on my system.

I will probably wrap the main in client in a script and move the libraries to the main Spotify folder in a later update.

**Comment by scaronni** [comment]
Ah, feedback is welcome :)

**Comment by sebbasttian** [comment]
Can confirm I can play local files now with this update

```
spotify-client.x86_64                 1:1.0-10.fc25            @fedora-spotify  
spotify-ffmpeg.x86_64                 0.10.16-2.fc25           @fedora-spotify  
spotify-openssl.x86_64                1.0.0t-2.fc25            @fedora-spotify 
 ```

Thank you very much! :thumbsup:
